// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBySource = `-- name: ActiveBySource :many
SELECT source_id, external_id, title, location_raw, country, url, departments, updated_at, content_hash, state, decision, function, seniority, confidence, reasons, first_seen, last_seen, closed_at FROM jobs
WHERE source_id = $1 AND state <> 'closed'
`

func (q *Queries) ActiveBySource(ctx context.Context, sourceID string) ([]Job, error) {
	rows, err := q.db.Query(ctx, activeBySource, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.SourceID,
			&i.ExternalID,
			&i.Title,
			&i.LocationRaw,
			&i.Country,
			&i.Url,
			&i.Departments,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.State,
			&i.Decision,
			&i.Function,
			&i.Seniority,
			&i.Confidence,
			&i.Reasons,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const closeJob = `-- name: CloseJob :exec

UPDATE jobs
SET state = 'closed', closed_at = now()
WHERE source_id = $1 AND external_id = $2
`

type CloseJobParams struct {
	SourceID   string
	ExternalID string
}

// first_seen is intentionally NOT updated: it records the original sighting.
func (q *Queries) CloseJob(ctx context.Context, arg CloseJobParams) error {
	_, err := q.db.Exec(ctx, closeJob, arg.SourceID, arg.ExternalID)
	return err
}

const listOpenJobs = `-- name: ListOpenJobs :many
SELECT source_id, external_id, title, location_raw, country, url, departments, updated_at, content_hash, state, decision, function, seniority, confidence, reasons, first_seen, last_seen, closed_at FROM jobs
WHERE state <> 'closed'
  AND ($2::text IS NULL OR decision = $2)
ORDER BY first_seen DESC
LIMIT $1
`

type ListOpenJobsParams struct {
	Limit    int32
	Decision pgtype.Text
}

// Powers the dashboard: all non-closed jobs, newest first. Filter by decision
// with the sqlc.narg (NULL => all decisions).
func (q *Queries) ListOpenJobs(ctx context.Context, arg ListOpenJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listOpenJobs, arg.Limit, arg.Decision)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.SourceID,
			&i.ExternalID,
			&i.Title,
			&i.LocationRaw,
			&i.Country,
			&i.Url,
			&i.Departments,
			&i.UpdatedAt,
			&i.ContentHash,
			&i.State,
			&i.Decision,
			&i.Function,
			&i.Seniority,
			&i.Confidence,
			&i.Reasons,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :exec
INSERT INTO jobs (
    source_id, external_id, title, location_raw, country, url, departments,
    updated_at, content_hash, state,
    decision, function, seniority, confidence, reasons,
    first_seen, last_seen, closed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18
)
ON CONFLICT (source_id, external_id) DO UPDATE SET
    title        = EXCLUDED.title,
    location_raw = EXCLUDED.location_raw,
    country      = EXCLUDED.country,
    url          = EXCLUDED.url,
    departments  = EXCLUDED.departments,
    updated_at   = EXCLUDED.updated_at,
    content_hash = EXCLUDED.content_hash,
    state        = EXCLUDED.state,
    decision     = EXCLUDED.decision,
    function     = EXCLUDED.function,
    seniority    = EXCLUDED.seniority,
    confidence   = EXCLUDED.confidence,
    reasons      = EXCLUDED.reasons,
    last_seen    = EXCLUDED.last_seen,
    closed_at    = EXCLUDED.closed_at
`

type UpsertJobParams struct {
	SourceID    string
	ExternalID  string
	Title       string
	LocationRaw string
	Country     string
	Url         string
	Departments []string
	UpdatedAt   pgtype.Timestamptz
	ContentHash string
	State       string
	Decision    string
	Function    string
	Seniority   string
	Confidence  float64
	Reasons     []string
	FirstSeen   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) error {
	_, err := q.db.Exec(ctx, upsertJob,
		arg.SourceID,
		arg.ExternalID,
		arg.Title,
		arg.LocationRaw,
		arg.Country,
		arg.Url,
		arg.Departments,
		arg.UpdatedAt,
		arg.ContentHash,
		arg.State,
		arg.Decision,
		arg.Function,
		arg.Seniority,
		arg.Confidence,
		arg.Reasons,
		arg.FirstSeen,
		arg.LastSeen,
		arg.ClosedAt,
	)
	return err
}
