// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	SourceID    string
	ExternalID  string
	Title       string
	LocationRaw string
	Country     string
	Url         string
	Departments []string
	UpdatedAt   pgtype.Timestamptz
	ContentHash string
	State       string
	Decision    string
	Function    string
	Seniority   string
	Confidence  float64
	Reasons     []string
	FirstSeen   pgtype.Timestamptz
	LastSeen    pgtype.Timestamptz
	ClosedAt    pgtype.Timestamptz
}

type NotificationOutbox struct {
	ID            int64
	JobSourceID   string
	JobExternalID string
	EventType     string
	Company       string
	Title         string
	Location      string
	Url           string
	Reasons       []string
	Status        string
	Attempts      int32
	NextAttempt   pgtype.Timestamptz
	LastError     string
	CreatedAt     pgtype.Timestamptz
	SentAt        pgtype.Timestamptz
}
