// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNotifications = `-- name: ClaimNotifications :many
UPDATE notification_outbox SET
    status = 'sending',
    attempts = attempts + 1,
    next_attempt = $2            -- visibility deadline: now() + timeout
WHERE id IN (
    SELECT id FROM notification_outbox
    WHERE status IN ('pending', 'sending') AND next_attempt <= now()
    ORDER BY next_attempt
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, job_source_id, job_external_id, event_type, company, title, location, url, reasons, status, attempts, next_attempt, last_error, created_at, sent_at
`

type ClaimNotificationsParams struct {
	Limit       int32
	NextAttempt pgtype.Timestamptz
}

// Atomically lease a batch of due notifications. Picks up both fresh 'pending'
// rows and 'sending' rows whose visibility deadline (next_attempt) has passed
// (crash recovery). SKIP LOCKED lets multiple dispatchers run safely.
func (q *Queries) ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, claimNotifications, arg.Limit, arg.NextAttempt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.JobSourceID,
			&i.JobExternalID,
			&i.EventType,
			&i.Company,
			&i.Title,
			&i.Location,
			&i.Url,
			&i.Reasons,
			&i.Status,
			&i.Attempts,
			&i.NextAttempt,
			&i.LastError,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueNotification = `-- name: EnqueueNotification :exec
INSERT INTO notification_outbox (
    job_source_id, job_external_id, event_type,
    company, title, location, url, reasons
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (job_source_id, job_external_id, event_type) DO NOTHING
`

type EnqueueNotificationParams struct {
	JobSourceID   string
	JobExternalID string
	EventType     string
	Company       string
	Title         string
	Location      string
	Url           string
	Reasons       []string
}

// Idempotent: a second enqueue for the same (job, event) is ignored.
func (q *Queries) EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error {
	_, err := q.db.Exec(ctx, enqueueNotification,
		arg.JobSourceID,
		arg.JobExternalID,
		arg.EventType,
		arg.Company,
		arg.Title,
		arg.Location,
		arg.Url,
		arg.Reasons,
	)
	return err
}

const failNotification = `-- name: FailNotification :exec
UPDATE notification_outbox
SET status = 'failed', last_error = $2
WHERE id = $1
`

type FailNotificationParams struct {
	ID        int64
	LastError string
}

func (q *Queries) FailNotification(ctx context.Context, arg FailNotificationParams) error {
	_, err := q.db.Exec(ctx, failNotification, arg.ID, arg.LastError)
	return err
}

const markSent = `-- name: MarkSent :exec
UPDATE notification_outbox
SET status = 'sent', sent_at = now(), last_error = ''
WHERE id = $1
`

func (q *Queries) MarkSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSent, id)
	return err
}

const rescheduleNotification = `-- name: RescheduleNotification :exec
UPDATE notification_outbox
SET status = 'pending', next_attempt = $2, last_error = $3
WHERE id = $1
`

type RescheduleNotificationParams struct {
	ID          int64
	NextAttempt pgtype.Timestamptz
	LastError   string
}

func (q *Queries) RescheduleNotification(ctx context.Context, arg RescheduleNotificationParams) error {
	_, err := q.db.Exec(ctx, rescheduleNotification, arg.ID, arg.NextAttempt, arg.LastError)
	return err
}
