// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ActiveBySource(ctx context.Context, sourceID string) ([]Job, error)
	// Atomically lease a batch of due notifications. Picks up both fresh 'pending'
	// rows and 'sending' rows whose visibility deadline (next_attempt) has passed
	// (crash recovery). SKIP LOCKED lets multiple dispatchers run safely.
	ClaimNotifications(ctx context.Context, arg ClaimNotificationsParams) ([]NotificationOutbox, error)
	// first_seen is intentionally NOT updated: it records the original sighting.
	CloseJob(ctx context.Context, arg CloseJobParams) error
	// Idempotent: a second enqueue for the same (job, event) is ignored.
	EnqueueNotification(ctx context.Context, arg EnqueueNotificationParams) error
	FailNotification(ctx context.Context, arg FailNotificationParams) error
	// Powers the dashboard: all non-closed jobs, newest first. Filter by decision
	// with the sqlc.narg (NULL => all decisions).
	ListOpenJobs(ctx context.Context, arg ListOpenJobsParams) ([]Job, error)
	MarkSent(ctx context.Context, id int64) error
	RescheduleNotification(ctx context.Context, arg RescheduleNotificationParams) error
	UpsertJob(ctx context.Context, arg UpsertJobParams) error
}

var _ Querier = (*Queries)(nil)
